[env:generic-esp32]
extends = blip, ledstrip, artnet, button, battery, script, espnow, power, ota, distance, io
build_flags = 
	${blip.build_flags}
	${ledstrip.build_flags}
	${artnet.build_flags}
	${fx.build_flags}
	${button.build_flags}
	${battery.build_flags}
	${script.build_flags}
	${espnow.build_flags}
	${power.build_flags}
	${ota.build_flags}
    ${distance.build_flags}
    ${io.build_flags}

	-D DEVICE_TYPE="\"ESP32 Generic\""
	-D DEVICE_CATEGORY="\"Generic\""

	; LED STRIP : dedicated to props so only one strip
    -D LEDSTRIP_FIXED_COUNT=1
    -D LED_BRIGHTNESS_FACTOR=0.8f
	-D LED_DEFAULT_COUNT=300
    -D LED_MAX_COUNT=400
	-D LED_DEFAULT_DATA_PIN=15

    -D DISTANCE_SENSOR_VL53L0X

lib_deps = 
	${blip.lib_deps}
	${ledstrip.lib_deps}
	${artnet.lib_deps}
	${script.lib_deps}
    ${distance.lib_deps}

[env:generic-xiaoc6]
extends = blip, c6board, ledstrip, artnet, button, battery, script, espnow, power, ota, distance, io
board = seeed_xiao_esp32c6
build_flags =
	${blip.build_flags}
	${c6board.build_flags}
	${ledstrip.build_flags}
	${artnet.build_flags}
	${fx.build_flags}
	${button.build_flags}
	${battery.build_flags}
	${script.build_flags}
	${espnow.build_flags}
	${power.build_flags}
	${ota.build_flags}
	${distance.build_flags}
	${io.build_flags}

	-D DEVICE_TYPE="\"XIAO C6 Generic\""
	-D DEVICE_CATEGORY="\"Generic\""

	-D WIFI_C6_USE_EXTERNAL_ANTENNA

	-D BUTTON_DEFAULT_PIN=2
	-D BATTERY_DEFAULT_PIN=0
	-D POWER_EXT=1
	-D POWER_WAKEUP_BUTTON=2
	-D POWER_WAKEUP_BUTTON_STATE=true

	; LED STRIP
	-D LED_USE_FASTLED
	-D LEDSTRIP_FIXED_COUNT=1
	-D LED_MODEL_SK9822
	-D LED_DEFAULT_DATA_PIN=17
	-D LED_DEFAULT_CLK_PIN=19
	-D LED_DEFAULT_COUNT=150
	-D LED_MAX_COUNT=1000
	-D LED_DEFAULT_COLOR_ORDER=BGR
	-D LED_DEFAULT_INVERT_DIRECTION=false
	-D LED_DEFAULT_BRIGHTNESS=0.6f
	-D LED_BRIGHTNESS_FACTOR=0.4f
	-D LED_DEFAULT_MAX_POWER=1600
	-D LED_LEDS_PER_PIXEL=1

	-D DISTANCE_SENSOR_VL53L0X

lib_deps =
	${blip.lib_deps}
	${ledstrip.lib_deps}
	${artnet.lib_deps}
	${script.lib_deps}
	${distance.lib_deps}
