[env:generic-esp32]
extends = blip, ledstrip, artnet, button, battery, script, espnow, power, ota, distance, io
build_flags = 
	${blip.build_flags}
	${ledstrip.build_flags}
	${artnet.build_flags}
	${fx.build_flags}
	${button.build_flags}
	${battery.build_flags}
	${script.build_flags}
	${espnow.build_flags}
	${power.build_flags}
	${ota.build_flags}
    ${distance.build_flags}
    ${io.build_flags}

	-D DEVICE_CATEGORY="\"Generic\""

	; LED STRIP : dedicated to props so only one strip
    -D LEDSTRIP_FIXED_COUNT=1
    -D LED_BRIGHTNESS_FACTOR=0.8f
	-D LED_DEFAULT_COUNT=300
    -D LED_MAX_COUNT=400
	-D LED_DEFAULT_DATA_PIN=15

    -D DISTANCE_SENSOR_VL53L0X

lib_deps = 
	${blip.lib_deps}
	${ledstrip.lib_deps}
	${artnet.lib_deps}
	${script.lib_deps}
    ${distance.lib_deps}